### ISSUE TITLE
Crash in cert_verify_cb()

### ISSUE THREAD

**Issue by linkmauve** [brunoos/luasec#130]
Here is a stack trace generated by Prosody running on ARM:
```gdb
Core was generated by `lua5.2 /usr/lib/prosody/../../bin/prosody'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00471efc in internshrstr (l=19, str=0xb6bfc2a8 "SSL:Verify:Registry", L=0x3ba2cd8) at lstring.c:137
137       for (o = g->strt.hash[lmod(h, g->strt.size)];
(gdb) bt
#0  0x00471efc in internshrstr (l=19, str=0xb6bfc2a8 "SSL:Verify:Registry", L=0x3ba2cd8) at lstring.c:137
#1  luaS_newlstr (L=L@entry=0x3ba2cd8, str=0xb6bfc2a8 "SSL:Verify:Registry", l=19) at lstring.c:158
#2  0x00472040 in luaS_new (L=L@entry=0x3ba2cd8, str=<optimized out>) at lstring.c:171
#3  0x00468004 in lua_getfield (L=L@entry=0x3ba2cd8, idx=<optimized out>, k=<optimized out>) at lapi.c:632                                                                                                          
#4  0xb6bf7ce0 in cert_verify_cb (x509_ctx=0x3d2a9d8, ptr=0x3eb27b0) at context.c:225
#5  0xb6b981c4 in ?? () from /usr/lib/libssl.so.1.1
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) bt full
#0  0x00471efc in internshrstr (l=19, str=0xb6bfc2a8 "SSL:Verify:Registry", L=0x3ba2cd8) at lstring.c:137
        o = <optimized out>
        g = 0x3ba2ca8
        h = 1407692308
        o = <optimized out>
        g = <optimized out>
        h = <optimized out>
        ts = <optimized out>
#1  luaS_newlstr (L=L@entry=0x3ba2cd8, str=0xb6bfc2a8 "SSL:Verify:Registry", l=19) at lstring.c:158
No locals.
#2  0x00472040 in luaS_new (L=L@entry=0x3ba2cd8, str=<optimized out>) at lstring.c:171
No locals.
#3  0x00468004 in lua_getfield (L=L@entry=0x3ba2cd8, idx=<optimized out>, k=<optimized out>) at lapi.c:632                                                                                                          
        io = 0x44
        x_ = <optimized out>
        t = 0x3ba2cd0
#4  0xb6bf7ce0 in cert_verify_cb (x509_ctx=0x3d2a9d8, ptr=0x3eb27b0) at context.c:225
        verify = <optimized out>
        L = 0x3ba2cd8
        ctx = 0x3eb27b0
        pctx = <optimized out>
#5  0xb6b981c4 in ?? () from /usr/lib/libssl.so.1.1
No symbol table info available.
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

I can rebuild OpenSSL with debug symbols if that’s of any use to debug this issue.

**Comment by linkmauve** [comment]
The caller is:
```
#5  0xb6b981c4 in d2i_SSL_SESSION (a=0x3d2a9d8, pp=0x3d2aa68, length=<optimized out>) at ssl/ssl_asn1.c:269
```

I have now rebuilt OpenSSL with debug symbols, the next time my Prosody server crashes I should be able to provide a full stack trace.

**Comment by Zash** [comment]
Was this with https://github.com/brunoos/luasec/commit/d4ea2d12f373ef95e0b790b487dde3a374d1b988 ?
The traceback in #75 looks somewhat similar.

**Comment by linkmauve** [comment]
It actually was 0.7, I just recompiled luasec master after yet another crash.  If you don’t hear from me again, this bug was probably fixed.

**Comment by brunoos** [comment]
I will close the issue.
You can open it again in any case.
