### ISSUE TITLE
Segmentation fault if ssl.config loded before ssl

### ISSUE THREAD

**Issue by Zash** [brunoos/luasec#148]
To reproduce:

```
~$ lua -l ssl.config
Segmentation fault
~$ lua -l ssl -l ssl.config
Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio
> 
```

Running under `gdb`:

```
(gdb) run
Starting program: /usr/bin/lua 
Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio
> require"ssl.config"
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x0000556fd9f13d00 in luaH_next (L=L@entry=0x556fdaaaf260, t=0x0, key=0x556fdaaaf620) at ltable.c:185
185	ltable.c: No such file or directory.
(gdb) bt
#0  0x0000556fd9f13d00 in luaH_next (L=L@entry=0x556fdaaaf260, t=0x0, key=0x556fdaaaf620) at ltable.c:185
#1  0x0000556fd9f0a23c in lua_next (L=L@entry=0x556fdaaaf260, idx=idx@entry=-2) at lapi.c:1120
#2  0x00007f5e6f9f7bcb in lsec_get_curves (L=L@entry=0x556fdaaaf260) at src/ec.c:91
#3  0x00007f5e6f9f7da6 in luaopen_ssl_config (L=0x556fdaaaf260) at src/config.c:65
#4  0x0000556fd9f0bf95 in luaD_precall (L=L@entry=0x556fdaaaf260, func=<optimized out>, nresults=1) at ldo.c:319
#5  0x0000556fd9f0c2b2 in luaD_call (L=L@entry=0x556fdaaaf260, func=<optimized out>, nResults=nResults@entry=1, allowyield=allowyield@entry=0) at ldo.c:401
#6  0x0000556fd9f09e2b in lua_callk (L=L@entry=0x556fdaaaf260, nargs=nargs@entry=2, nresults=nresults@entry=1, ctx=ctx@entry=0, k=k@entry=0x0) at lapi.c:905
#7  0x0000556fd9f24dc7 in ll_require (L=0x556fdaaaf260) at loadlib.c:520
#8  0x0000556fd9f0bf95 in luaD_precall (L=L@entry=0x556fdaaaf260, func=<optimized out>, func@entry=0x556fdaaaf570, nresults=nresults@entry=0) at ldo.c:319
#9  0x0000556fd9f16725 in luaV_execute (L=L@entry=0x556fdaaaf260) at lvm.c:709
#10 0x0000556fd9f0c2be in luaD_call (L=0x556fdaaaf260, func=<optimized out>, nResults=<optimized out>, allowyield=<optimized out>) at ldo.c:402
#11 0x0000556fd9f0b8ef in luaD_rawrunprotected (L=L@entry=0x556fdaaaf260, f=f@entry=0x556fd9f08910 <f_call>, ud=ud@entry=0x7ffc3f805dc0) at ldo.c:131
#12 0x0000556fd9f0c521 in luaD_pcall (L=L@entry=0x556fdaaaf260, func=func@entry=0x556fd9f08910 <f_call>, u=u@entry=0x7ffc3f805dc0, old_top=48, ef=<optimized out>) at ldo.c:603
#13 0x0000556fd9f09ef1 in lua_pcallk (L=0x556fdaaaf260, nargs=<optimized out>, nresults=-1, errfunc=<optimized out>, ctx=<optimized out>, k=<optimized out>) at lapi.c:949
#14 0x0000556fd9f07b26 in docall (L=0x556fdaaaf260, narg=0, nres=-1) at lua.c:179
#15 0x0000556fd9f080a3 in dotty (L=0x556fdaaaf260) at lua.c:308
#16 0x0000556fd9f0856d in pmain (L=0x556fdaaaf260) at lua.c:471
#17 0x0000556fd9f0bf95 in luaD_precall (L=L@entry=0x556fdaaaf260, func=<optimized out>, nresults=1) at ldo.c:319
#18 0x0000556fd9f0c2b2 in luaD_call (L=0x556fdaaaf260, func=<optimized out>, nResults=<optimized out>, allowyield=<optimized out>) at ldo.c:401
#19 0x0000556fd9f0b8ef in luaD_rawrunprotected (L=L@entry=0x556fdaaaf260, f=f@entry=0x556fd9f08910 <f_call>, ud=ud@entry=0x7ffc3f8060b0) at ldo.c:131
#20 0x0000556fd9f0c521 in luaD_pcall (L=L@entry=0x556fdaaaf260, func=func@entry=0x556fd9f08910 <f_call>, u=u@entry=0x7ffc3f8060b0, old_top=16, ef=<optimized out>) at ldo.c:603
#21 0x0000556fd9f09ef1 in lua_pcallk (L=0x556fdaaaf260, nargs=<optimized out>, nresults=1, errfunc=<optimized out>, ctx=<optimized out>, k=<optimized out>) at lapi.c:949
#22 0x0000556fd9f0789b in main (argc=1, argv=0x7ffc3f8061e8) at lua.c:491
(gdb) bt full 3
#0  0x0000556fd9f13d00 in luaH_next (L=L@entry=0x556fdaaaf260, t=0x0, key=0x556fdaaaf620) at ltable.c:185
        i = <optimized out>
        io2 = <optimized out>
        io1 = <optimized out>
#1  0x0000556fd9f0a23c in lua_next (L=L@entry=0x556fdaaaf260, idx=idx@entry=-2) at lapi.c:1120
        t = <optimized out>
        more = 0
#2  0x00007f5e6f9f7bcb in lsec_get_curves (L=L@entry=0x556fdaaaf260) at src/ec.c:91
No locals.
(More stack frames follow...)
(gdb) 

```

**Comment by brunoos** [comment]
You should not require "ssl.config" directly, the module "ssl" does it and you access "ssl.config".
